<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\..\Users\oso79\Pictures\sample.png" Link="Assets\Image\sample.png" />
  </ItemGroup>

	<ItemGroup>

		<ItemGroup>

			<!--
  WPF 프로젝트의 appsettings.json을
  빌드 결과 폴더와 Publish 결과 폴더에 복사한다.

  SDK 프로젝트에서는 일반 JSON 파일이
  기본적으로 None 항목에 포함되므로
  Content가 아니라 None Update를 사용한다.
  -->
			<None Update="appsettings.json">

				<!--
    Debug 또는 Release 빌드 결과 폴더에 복사한다.
    -->
				<CopyToOutputDirectory>
					PreserveNewest
				</CopyToOutputDirectory>

				<!--
    dotnet publish 결과 폴더에도 복사한다.
    -->
				<CopyToPublishDirectory>
					PreserveNewest
				</CopyToPublishDirectory>

			</None>

		</ItemGroup>
	
	


  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4078.44" />
  </ItemGroup>

</Project>
