<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="..\..\..\Users\oso79\Pictures\sample.png"
				 Link="Assets\Image\sample.png" />
	</ItemGroup>

	<!--
  appsettings.json을 빌드 및 Publish 결과 폴더에 복사한다.
  -->
	<ItemGroup>
		<None Update="appsettings.json">

			<!--
      Debug 또는 Release 빌드 결과 폴더에 복사한다.
      -->
			<CopyToOutputDirectory>
				PreserveNewest
			</CopyToOutputDirectory>

			<!--
      dotnet publish 결과 폴더에 복사한다.
      -->
			<CopyToPublishDirectory>
				PreserveNewest
			</CopyToPublishDirectory>

		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Web.WebView2"
						  Version="1.0.4078.44" />
	</ItemGroup>

</Project>