/*
 * Popup System - PostgreSQL initial schema v0.8
 * Target database: zero-rule
 * Target schema: popup_db
 *
 * Run this file while connected to the zero-rule server database.
 * Data migration is performed separately with DBeaver.
 */

CREATE SCHEMA IF NOT EXISTS popup_db;

-- Keep every unqualified popup object inside popup_db for this session.
-- pg_catalog is retained so PostgreSQL built-in objects resolve normally.
SET search_path TO popup_db, pg_catalog;

BEGIN;

CREATE TABLE app_department
(
    department_id        VARCHAR(30)  NOT NULL,
    parent_department_id VARCHAR(30),
    department_name      VARCHAR(100) NOT NULL,
    department_level     INTEGER      NOT NULL,
    sort_order           INTEGER      NOT NULL,
    active_yn            CHAR(1)      NOT NULL DEFAULT 'Y',
    created_by           VARCHAR(30)  NOT NULL,
    created_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by           VARCHAR(30)  NOT NULL,
    updated_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_app_department PRIMARY KEY (department_id),
    CONSTRAINT fk_department_parent
        FOREIGN KEY (parent_department_id)
        REFERENCES app_department (department_id),
    CONSTRAINT ck_department_level CHECK (department_level >= 1),
    CONSTRAINT ck_department_sort_order CHECK (sort_order >= 0),
    CONSTRAINT ck_department_active CHECK (active_yn IN ('Y', 'N'))
);

CREATE TABLE app_position
(
    position_id   VARCHAR(30)  NOT NULL,
    position_name VARCHAR(100) NOT NULL,
    sort_order    INTEGER      NOT NULL,
    active_yn     CHAR(1)      NOT NULL DEFAULT 'Y',
    created_by    VARCHAR(30)  NOT NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by    VARCHAR(30)  NOT NULL,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_app_position PRIMARY KEY (position_id),
    CONSTRAINT ck_position_sort_order CHECK (sort_order >= 0),
    CONSTRAINT ck_position_active CHECK (active_yn IN ('Y', 'N'))
);

CREATE TABLE app_user
(
    employee_no   VARCHAR(30)  NOT NULL,
    employee_name VARCHAR(100) NOT NULL,
    department_id VARCHAR(30)  NOT NULL,
    position_id   VARCHAR(30)  NOT NULL,
    active_yn     CHAR(1)      NOT NULL DEFAULT 'Y',
    hire_date     DATE,
    last_login_at TIMESTAMP,
    created_by    VARCHAR(30)  NOT NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by    VARCHAR(30)  NOT NULL,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_app_user PRIMARY KEY (employee_no),
    CONSTRAINT fk_user_department
        FOREIGN KEY (department_id)
        REFERENCES app_department (department_id),
    CONSTRAINT fk_user_position
        FOREIGN KEY (position_id)
        REFERENCES app_position (position_id),
    CONSTRAINT ck_user_active CHECK (active_yn IN ('Y', 'N'))
);

CREATE TABLE question_template
(
    question_template_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    template_group_id    VARCHAR(30)  NOT NULL,
    template_name        VARCHAR(100) NOT NULL,
    template_type        VARCHAR(10)  NOT NULL,
    template_version     INTEGER      NOT NULL,
    current_yn           CHAR(1)      NOT NULL DEFAULT 'Y',
    active_yn            CHAR(1)      NOT NULL DEFAULT 'Y',
    created_by           VARCHAR(30)  NOT NULL,
    created_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by           VARCHAR(30)  NOT NULL,
    updated_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_question_template PRIMARY KEY (question_template_id),
    CONSTRAINT uk_question_template_group_version
        UNIQUE (template_group_id, template_version),
    CONSTRAINT ck_question_template_version CHECK (template_version >= 1),
    CONSTRAINT ck_question_template_current CHECK (current_yn IN ('Y', 'N')),
    CONSTRAINT ck_question_template_active CHECK (active_yn IN ('Y', 'N'))
);

CREATE UNIQUE INDEX ux_question_template_current
    ON question_template (template_group_id)
    WHERE current_yn = 'Y';

CREATE TABLE popup_notice
(
    popup_id                       VARCHAR(50)  NOT NULL,
    question_template_id           BIGINT,
    popup_type                     VARCHAR(20)  NOT NULL,
    title                          VARCHAR(200) NOT NULL,
    show_on_login_yn               CHAR(1)      NOT NULL DEFAULT 'N',
    show_on_schedule_yn            CHAR(1)      NOT NULL DEFAULT 'N',
    scheduled_at                   TIMESTAMP,
    display_start_at               TIMESTAMP    NOT NULL,
    display_end_at                 TIMESTAMP    NOT NULL,
    display_mode                   VARCHAR(20)  NOT NULL,
    period_mode                    VARCHAR(20)  NOT NULL,
    repeat_interval                INTEGER,
    repeat_day_of_week             VARCHAR(20),
    repeat_day_of_month            INTEGER,
    active_yn                      CHAR(1)      NOT NULL DEFAULT 'Y',
    size_mode                      VARCHAR(30)  NOT NULL,
    popup_width                    NUMERIC(10,2),
    popup_height                   NUMERIC(10,2),
    width_ratio                    NUMERIC(5,4),
    height_ratio                   NUMERIC(5,4),
    minimum_width                  NUMERIC(10,2),
    minimum_height                 NUMERIC(10,2),
    maximum_width                  NUMERIC(10,2),
    maximum_height                 NUMERIC(10,2),
    show_header_yn                 CHAR(1)      NOT NULL DEFAULT 'Y',
    show_close_button_yn           CHAR(1)      NOT NULL DEFAULT 'Y',
    show_footer_yn                 CHAR(1)      NOT NULL DEFAULT 'Y',
    show_do_not_show_again_yn      CHAR(1)      NOT NULL DEFAULT 'N',
    hide_days                      INTEGER,
    completion_ratio               NUMERIC(5,4),
    passing_score                  NUMERIC(10,2),
    allow_close_before_complete_yn CHAR(1)      NOT NULL DEFAULT 'Y',
    created_by                     VARCHAR(30)  NOT NULL,
    created_at                     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by                     VARCHAR(30)  NOT NULL,
    updated_at                     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_popup_notice PRIMARY KEY (popup_id),
    CONSTRAINT fk_popup_question_template
        FOREIGN KEY (question_template_id)
        REFERENCES question_template (question_template_id),
    CONSTRAINT ck_popup_display_period CHECK (display_end_at >= display_start_at),
    CONSTRAINT ck_popup_scheduled_at CHECK
        (show_on_schedule_yn = 'N' OR scheduled_at IS NOT NULL),
    CONSTRAINT ck_popup_repeat_interval CHECK
        (repeat_interval IS NULL OR repeat_interval >= 1),
    CONSTRAINT ck_popup_repeat_day_of_month CHECK
        (repeat_day_of_month IS NULL OR repeat_day_of_month BETWEEN 1 AND 31),
    CONSTRAINT ck_popup_hide_days CHECK (hide_days IS NULL OR hide_days >= 1),
    CONSTRAINT ck_popup_completion_ratio CHECK
        (completion_ratio IS NULL OR completion_ratio BETWEEN 0 AND 1),
    CONSTRAINT ck_popup_passing_score CHECK
        (passing_score IS NULL OR passing_score >= 0),
    CONSTRAINT ck_popup_width_ratio CHECK
        (width_ratio IS NULL OR width_ratio > 0),
    CONSTRAINT ck_popup_height_ratio CHECK
        (height_ratio IS NULL OR height_ratio > 0),
    CONSTRAINT ck_popup_yn_values CHECK
        (show_on_login_yn IN ('Y', 'N')
         AND show_on_schedule_yn IN ('Y', 'N')
         AND active_yn IN ('Y', 'N')
         AND show_header_yn IN ('Y', 'N')
         AND show_close_button_yn IN ('Y', 'N')
         AND show_footer_yn IN ('Y', 'N')
         AND show_do_not_show_again_yn IN ('Y', 'N')
         AND allow_close_before_complete_yn IN ('Y', 'N'))
);

CREATE TABLE popup_content
(
    popup_id        VARCHAR(50) NOT NULL,
    content_title   VARCHAR(200),
    description     VARCHAR(2000),
    content_body    TEXT,
    media_url       VARCHAR(2000),
    link_url        VARCHAR(2000),
    content_options JSONB,
    created_by      VARCHAR(30) NOT NULL,
    created_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by      VARCHAR(30) NOT NULL,
    updated_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_popup_content PRIMARY KEY (popup_id),
    CONSTRAINT fk_content_popup
        FOREIGN KEY (popup_id)
        REFERENCES popup_notice (popup_id)
        ON DELETE CASCADE
);

CREATE TABLE popup_target_group
(
    target_group_id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    popup_id          VARCHAR(50)  NOT NULL,
    target_name       VARCHAR(100) NOT NULL,
    target_description VARCHAR(500) NOT NULL,
    group_order       INTEGER      NOT NULL,
    created_by        VARCHAR(30)  NOT NULL,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by        VARCHAR(30)  NOT NULL,
    updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_popup_target_group PRIMARY KEY (target_group_id),
    CONSTRAINT fk_target_group_popup
        FOREIGN KEY (popup_id)
        REFERENCES popup_notice (popup_id)
        ON DELETE CASCADE,
    CONSTRAINT uq_target_group_order UNIQUE (popup_id, group_order),
    CONSTRAINT ck_target_group_order CHECK (group_order >= 1)
);

CREATE TABLE popup_target_condition
(
    target_condition_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    target_group_id     BIGINT      NOT NULL,
    condition_type      VARCHAR(30) NOT NULL,
    condition_operator  VARCHAR(10) NOT NULL,
    department_id       VARCHAR(30),
    position_id         VARCHAR(30),
    employee_no         VARCHAR(30),
    condition_date_value DATE,
    include_child_yn    CHAR(1)     NOT NULL DEFAULT 'N',
    condition_order     INTEGER     NOT NULL,
    created_by          VARCHAR(30) NOT NULL,
    created_at          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by          VARCHAR(30) NOT NULL,
    updated_at          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_popup_target_condition PRIMARY KEY (target_condition_id),
    CONSTRAINT fk_target_condition_group
        FOREIGN KEY (target_group_id)
        REFERENCES popup_target_group (target_group_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_target_condition_department
        FOREIGN KEY (department_id)
        REFERENCES app_department (department_id),
    CONSTRAINT fk_target_condition_position
        FOREIGN KEY (position_id)
        REFERENCES app_position (position_id),
    CONSTRAINT fk_target_condition_employee
        FOREIGN KEY (employee_no)
        REFERENCES app_user (employee_no),
    CONSTRAINT uq_target_condition_order UNIQUE (target_group_id, condition_order),
    CONSTRAINT ck_target_condition_order CHECK (condition_order >= 1),
    CONSTRAINT ck_target_condition_include_child CHECK (include_child_yn IN ('Y', 'N')),
    CONSTRAINT ck_target_condition_operator CHECK
        (condition_operator IN ('=', '!=', '<', '<=', '>', '>=')),
    CONSTRAINT ck_target_condition_value CHECK
    (
        num_nonnulls(department_id, position_id, employee_no, condition_date_value) = 1
        AND
        CASE condition_type
            WHEN 'DEPARTMENT' THEN department_id IS NOT NULL
            WHEN 'POSITION'   THEN position_id IS NOT NULL
            WHEN 'EMPLOYEE'   THEN employee_no IS NOT NULL
            WHEN 'HIRE_DATE'  THEN condition_date_value IS NOT NULL
            ELSE FALSE
        END
    ),
    CONSTRAINT ck_target_condition_child_department CHECK
        (include_child_yn = 'N' OR condition_type = 'DEPARTMENT')
);

CREATE TABLE popup_question
(
    question_id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    question_template_id BIGINT        NOT NULL,
    question_type        VARCHAR(30)   NOT NULL,
    question_title       VARCHAR(1000) NOT NULL,
    question_description VARCHAR(2000),
    required_yn          CHAR(1)       NOT NULL DEFAULT 'N',
    scored_yn            CHAR(1)       NOT NULL DEFAULT 'N',
    question_score       NUMERIC(10,2),
    sort_order           INTEGER       NOT NULL,
    created_by           VARCHAR(30)   NOT NULL,
    created_at           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by           VARCHAR(30)   NOT NULL,
    updated_at           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_popup_question PRIMARY KEY (question_id),
    CONSTRAINT fk_question_template
        FOREIGN KEY (question_template_id)
        REFERENCES question_template (question_template_id)
        ON DELETE CASCADE,
    CONSTRAINT uq_question_sort_order UNIQUE (question_template_id, sort_order),
    CONSTRAINT ck_question_sort_order CHECK (sort_order >= 1),
    CONSTRAINT ck_question_yn_values CHECK
        (required_yn IN ('Y', 'N') AND scored_yn IN ('Y', 'N')),
    CONSTRAINT ck_question_score CHECK
        ((scored_yn = 'Y' AND question_score IS NOT NULL AND question_score >= 0)
         OR (scored_yn = 'N' AND question_score IS NULL))
);

CREATE TABLE popup_option
(
    option_id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    question_id  BIGINT        NOT NULL,
    option_value VARCHAR(200)   NOT NULL,
    option_text  VARCHAR(1000)  NOT NULL,
    correct_yn   CHAR(1)        NOT NULL DEFAULT 'N',
    sort_order   INTEGER        NOT NULL,
    created_by   VARCHAR(30)    NOT NULL,
    created_at   TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by   VARCHAR(30)    NOT NULL,
    updated_at   TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_popup_option PRIMARY KEY (option_id),
    CONSTRAINT fk_option_question
        FOREIGN KEY (question_id)
        REFERENCES popup_question (question_id)
        ON DELETE CASCADE,
    CONSTRAINT uq_option_value UNIQUE (question_id, option_value),
    CONSTRAINT uq_option_sort_order UNIQUE (question_id, sort_order),
    CONSTRAINT ck_option_sort_order CHECK (sort_order >= 1),
    CONSTRAINT ck_option_correct CHECK (correct_yn IN ('Y', 'N'))
);

CREATE TABLE user_popup_status
(
    user_popup_status_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    employee_no          VARCHAR(30) NOT NULL,
    popup_id             VARCHAR(50) NOT NULL,
    popup_status         VARCHAR(30) NOT NULL,
    first_displayed_at   TIMESTAMP,
    last_displayed_at    TIMESTAMP,
    display_count        INTEGER     NOT NULL DEFAULT 0,
    closed_at            TIMESTAMP,
    hidden_from_at       TIMESTAMP,
    hidden_until_at      TIMESTAMP,
    completed_yn         CHAR(1)     NOT NULL DEFAULT 'N',
    completed_at         TIMESTAMP,
    created_by           VARCHAR(30) NOT NULL,
    created_at           TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by           VARCHAR(30) NOT NULL,
    updated_at           TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_user_popup_status PRIMARY KEY (user_popup_status_id),
    CONSTRAINT uq_user_popup_status UNIQUE (employee_no, popup_id),
    CONSTRAINT fk_status_user
        FOREIGN KEY (employee_no)
        REFERENCES app_user (employee_no),
    CONSTRAINT fk_status_popup
        FOREIGN KEY (popup_id)
        REFERENCES popup_notice (popup_id)
        ON DELETE CASCADE,
    CONSTRAINT ck_status_display_count CHECK (display_count >= 0),
    CONSTRAINT ck_status_completed CHECK (completed_yn IN ('Y', 'N')),
    CONSTRAINT ck_status_hidden_period CHECK
        (hidden_until_at IS NULL OR hidden_from_at IS NULL OR hidden_until_at >= hidden_from_at)
);

CREATE TABLE popup_response
(
    response_id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    client_request_id    VARCHAR(100) NOT NULL,
    popup_id             VARCHAR(50)  NOT NULL,
    employee_no          VARCHAR(30)  NOT NULL,
    question_template_id BIGINT,
    response_status      VARCHAR(30)  NOT NULL,
    response_started_at  TIMESTAMP,
    submitted_at         TIMESTAMP,
    received_at          TIMESTAMP,
    total_score          NUMERIC(10,2),
    passed_yn            CHAR(1),
    created_by           VARCHAR(30)  NOT NULL,
    created_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by           VARCHAR(30)  NOT NULL,
    updated_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_popup_response PRIMARY KEY (response_id),
    CONSTRAINT uq_response_request UNIQUE (client_request_id),
    CONSTRAINT uq_response_user_popup UNIQUE (employee_no, popup_id),
    CONSTRAINT fk_response_popup
        FOREIGN KEY (popup_id)
        REFERENCES popup_notice (popup_id),
    CONSTRAINT fk_response_user
        FOREIGN KEY (employee_no)
        REFERENCES app_user (employee_no),
    CONSTRAINT fk_response_question_template
        FOREIGN KEY (question_template_id)
        REFERENCES question_template (question_template_id),
    CONSTRAINT ck_response_passed CHECK (passed_yn IS NULL OR passed_yn IN ('Y', 'N')),
    CONSTRAINT ck_response_total_score CHECK (total_score IS NULL OR total_score >= 0)
);

CREATE TABLE popup_response_answer
(
    response_answer_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    response_id        BIGINT       NOT NULL,
    question_id        BIGINT       NOT NULL,
    text_answer        TEXT,
    earned_score       NUMERIC(10,2),
    correct_yn         CHAR(1),
    created_by         VARCHAR(30) NOT NULL,
    created_at         TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by         VARCHAR(30) NOT NULL,
    updated_at         TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_popup_response_answer PRIMARY KEY (response_answer_id),
    CONSTRAINT uq_response_question UNIQUE (response_id, question_id),
    CONSTRAINT fk_answer_response
        FOREIGN KEY (response_id)
        REFERENCES popup_response (response_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_answer_question
        FOREIGN KEY (question_id)
        REFERENCES popup_question (question_id),
    CONSTRAINT ck_answer_earned_score CHECK (earned_score IS NULL OR earned_score >= 0),
    CONSTRAINT ck_answer_correct CHECK (correct_yn IS NULL OR correct_yn IN ('Y', 'N'))
);

CREATE TABLE popup_response_value
(
    response_value_id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    response_answer_id BIGINT       NOT NULL,
    option_id          BIGINT,
    selected_value     VARCHAR(200) NOT NULL,
    created_by         VARCHAR(30) NOT NULL,
    created_at         TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by         VARCHAR(30) NOT NULL,
    updated_at         TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_popup_response_value PRIMARY KEY (response_value_id),
    CONSTRAINT fk_value_answer
        FOREIGN KEY (response_answer_id)
        REFERENCES popup_response_answer (response_answer_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_value_option
        FOREIGN KEY (option_id)
        REFERENCES popup_option (option_id)
);

CREATE TABLE video_view_status
(
    video_view_status_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    employee_no              VARCHAR(30)   NOT NULL,
    popup_id                 VARCHAR(50)   NOT NULL,
    total_duration_seconds   NUMERIC(12,3),
    last_position_seconds    NUMERIC(12,3),
    maximum_position_seconds NUMERIC(12,3),
    watched_seconds          NUMERIC(12,3),
    watched_ratio            NUMERIC(5,4),
    completed_yn             CHAR(1)       NOT NULL DEFAULT 'N',
    first_played_at          TIMESTAMP,
    last_played_at           TIMESTAMP,
    completed_at             TIMESTAMP,
    created_by               VARCHAR(30)   NOT NULL,
    created_at               TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by               VARCHAR(30)   NOT NULL,
    updated_at               TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_video_view_status PRIMARY KEY (video_view_status_id),
    CONSTRAINT uq_video_view_status UNIQUE (employee_no, popup_id),
    CONSTRAINT fk_video_status_user
        FOREIGN KEY (employee_no)
        REFERENCES app_user (employee_no),
    CONSTRAINT fk_video_status_popup
        FOREIGN KEY (popup_id)
        REFERENCES popup_notice (popup_id)
        ON DELETE CASCADE,
    CONSTRAINT ck_video_completed CHECK (completed_yn IN ('Y', 'N')),
    CONSTRAINT ck_video_duration CHECK
        (total_duration_seconds IS NULL OR total_duration_seconds >= 0),
    CONSTRAINT ck_video_last_position CHECK
        (last_position_seconds IS NULL OR last_position_seconds >= 0),
    CONSTRAINT ck_video_maximum_position CHECK
        (maximum_position_seconds IS NULL OR maximum_position_seconds >= 0),
    CONSTRAINT ck_video_watched_seconds CHECK
        (watched_seconds IS NULL OR watched_seconds >= 0),
    CONSTRAINT ck_video_watched_ratio CHECK
        (watched_ratio IS NULL OR watched_ratio BETWEEN 0 AND 1)
);

CREATE TABLE api_request_log
(
    api_request_log_id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    client_request_id    VARCHAR(100),
    employee_no          VARCHAR(30),
    popup_id             VARCHAR(50),
    api_path             VARCHAR(1000) NOT NULL,
    http_method          VARCHAR(10)   NOT NULL,
    client_ip            VARCHAR(100),
    request_received_at  TIMESTAMP     NOT NULL,
    response_completed_at TIMESTAMP,
    elapsed_milliseconds BIGINT,
    http_status_code     INTEGER,
    success_yn           CHAR(1)       NOT NULL,
    error_code           VARCHAR(100),
    error_message        TEXT,
    request_summary      TEXT,
    response_summary     TEXT,
    created_by           VARCHAR(30)   NOT NULL,
    created_at           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by           VARCHAR(30)   NOT NULL,
    updated_at           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_api_request_log PRIMARY KEY (api_request_log_id),
    CONSTRAINT fk_api_log_user
        FOREIGN KEY (employee_no)
        REFERENCES app_user (employee_no),
    CONSTRAINT fk_api_log_popup
        FOREIGN KEY (popup_id)
        REFERENCES popup_notice (popup_id),
    CONSTRAINT ck_api_log_elapsed CHECK
        (elapsed_milliseconds IS NULL OR elapsed_milliseconds >= 0),
    CONSTRAINT ck_api_log_status CHECK
        (http_status_code IS NULL OR http_status_code BETWEEN 100 AND 599),
    CONSTRAINT ck_api_log_success CHECK (success_yn IN ('Y', 'N'))
);

CREATE INDEX ix_department_parent
    ON app_department (parent_department_id);
CREATE INDEX ix_user_department
    ON app_user (department_id);
CREATE INDEX ix_user_position
    ON app_user (position_id);
CREATE INDEX ix_popup_display_period
    ON popup_notice (active_yn, display_start_at, display_end_at);
CREATE INDEX ix_popup_template
    ON popup_notice (question_template_id);
CREATE INDEX ix_target_group_popup
    ON popup_target_group (popup_id);
CREATE INDEX ix_target_condition_group
    ON popup_target_condition (target_group_id);
CREATE INDEX ix_question_template
    ON popup_question (question_template_id, sort_order);
CREATE INDEX ix_option_question
    ON popup_option (question_id, sort_order);
CREATE INDEX ix_status_popup
    ON user_popup_status (popup_id);
CREATE INDEX ix_response_popup_user
    ON popup_response (popup_id, employee_no);
CREATE INDEX ix_answer_response
    ON popup_response_answer (response_id);
CREATE INDEX ix_value_answer
    ON popup_response_value (response_answer_id);
CREATE INDEX ix_video_popup
    ON video_view_status (popup_id);
CREATE INDEX ix_api_log_received_at
    ON api_request_log (request_received_at);

COMMENT ON TABLE question_template IS 'Reusable and versioned question template';
COMMENT ON COLUMN popup_target_condition.condition_date_value IS
    'Comparison date used when CONDITION_TYPE is HIRE_DATE';

COMMIT;

RESET search_path;
